"""Atlassian Design System (ADS) and data-testid Element Selectors for UI Testing.
Compliant with Section 19 (UI Information Architecture) and R-30 / R-31.
"""

# Authentication
AUTH_USERNAME_INPUT = '[data-testid="login-username-input"]'
AUTH_PASSWORD_INPUT = '[data-testid="login-password-input"]'
AUTH_SUBMIT_BUTTON = '[data-testid="login-submit-button"]'
AUTH_ERROR_BANNER = '[data-testid="login-error-banner"]'
AUTH_LOGOUT_BUTTON = '[data-testid="header-logout-button"]'

# Navigation & Queues
NAV_INBOX_READY = '[data-testid="queue-nav-ready-to-review"]'
NAV_INBOX_MANUAL = '[data-testid="queue-nav-needs-manual-review"]'
NAV_INBOX_PRODUCT = '[data-testid="queue-nav-product-inquiry"]'
NAV_INBOX_RECENT_ORDER = '[data-testid="queue-nav-recent-order"]'
NAV_INBOX_COMPLAINT = '[data-testid="queue-nav-complaint"]'
NAV_INBOX_SPAM = '[data-testid="queue-nav-spam"]'
NAV_INBOX_SENT = '[data-testid="queue-nav-sent"]'
NAV_SETTINGS = '[data-testid="nav-settings"]'

# Store Setup Wizard
WIZARD_ADD_STORE_BTN = '[data-testid="wizard-add-store-button"]'
WIZARD_STEP1_CONTAINER = '[data-testid="wizard-step1-container"]'
WIZARD_STORE_NAME_INPUT = '[data-testid="wizard-store-name"]'
STORE_NAME_INPUT = '[data-testid="wizard-store-name"]'
WIZARD_PUBLIC_DOMAIN_INPUT = '[data-testid="wizard-public-domain"]'
STORE_DOMAIN_INPUT = '[data-testid="wizard-public-domain"]'
WIZARD_CANONICAL_DOMAIN_INPUT = '[data-testid="wizard-canonical-domain"]'
WIZARD_MAILBOX_ADDRESS_INPUT = '[data-testid="wizard-mailbox-address"]'
WIZARD_TEST_MAILBOX_BTN = '[data-testid="wizard-test-mailbox-button"]'

WIZARD_STEP2_CONTAINER = '[data-testid="wizard-step2-container"]'
PROXY_HOST_INPUT = '[data-testid="proxy-host-input"]'
PROXY_PORT_INPUT = '[data-testid="proxy-port-input"]'
PROXY_USERNAME_INPUT = '[data-testid="proxy-username-input"]'
PROXY_PASSWORD_INPUT = '[data-testid="proxy-password-input"]'
WIZARD_TEST_PROXY_BTN = '[data-testid="wizard-test-proxy-button"]'
PROXY_TEST_BUTTON = '[data-testid="wizard-test-proxy-button"]'

WIZARD_STEP3_CONTAINER = '[data-testid="wizard-step3-container"]'
SHOPIFY_CLIENT_ID_INPUT = '[data-testid="shopify-client-id-input"]'
SHOPIFY_CLIENT_SECRET_INPUT = '[data-testid="shopify-client-secret-input"]'
WIZARD_TEST_SHOPIFY_BTN = '[data-testid="wizard-test-shopify-button"]'
SHOPIFY_TEST_BUTTON = '[data-testid="wizard-test-shopify-button"]'

WIZARD_STEP4_CONTAINER = '[data-testid="wizard-step4-container"]'
WIZARD_ACTIVATE_BTN = '[data-testid="wizard-activate-button"]'
WIZARD_FINISH_BUTTON = '[data-testid="wizard-activate-button"]'
WIZARD_SUCCESS_BANNER = '[data-testid="wizard-success-banner"]'

WIZARD_NEXT_BUTTON = '[data-testid="wizard-next-button"]'
WIZARD_BACK_BUTTON = '[data-testid="wizard-back-button"]'

# Email Detail & Evidence Panel
EMAIL_LIST_ROW_FIRST = '[data-testid="email-list-row"]:first-child'
EMAIL_BODY_VIEWER = '[data-testid="email-body-content"]'
EVIDENCE_PANEL = '[data-testid="evidence-panel"]'
BADGE_INTENT = '[data-testid="badge-intent"]'
BADGE_SPAM_STATUS = '[data-testid="badge-spam-status"]'
BADGE_ORDER_STATUS = '[data-testid="badge-order-status"]'
# Shopify Enrichment & Policies (Phase 5)
ORDER_FACTS_SNAPSHOT = '[data-testid="order-facts-snapshot"]'
STALE_DRAFT_ALERT_BANNER = '[data-testid="stale-draft-alert-banner"]'
REGENERATE_DRAFT_BTN = '[data-testid="button-regenerate-draft-latest-policies"]'
PRODUCT_FACTS_SNAPSHOT = '[data-testid="product-facts-snapshot"]'
PRODUCT_NOT_RESOLVED_BANNER = '[data-testid="product-not-resolved-banner"]'
ORDER_FLAG_PAID = '[data-testid="flag-paid"]'
ORDER_FLAG_ACTIVE = '[data-testid="flag-active"]'
ORDER_FLAG_CANCELLED = '[data-testid="flag-cancelled"]'
ORDER_FLAG_REFUNDED = '[data-testid="flag-refunded"]'
ORDER_FLAG_FULFILLED = '[data-testid="flag-fulfilled"]'
LOOKUP_CHECKED_AT = '[data-testid="lookup-checked-at"]'

# Backward compatibility aliases
ORDER_DETAILS_CARD = ORDER_FACTS_SNAPSHOT
POLICY_WARNING_BANNER = STALE_DRAFT_ALERT_BANNER

# Draft Editor & Sending
DRAFT_EDITOR_TEXTAREA = '[data-testid="draft-editor-textarea"]'
DRAFT_SAVE_BUTTON = '[data-testid="draft-save-button"]'
DRAFT_REGENERATE_BUTTON = '[data-testid="draft-regenerate-button"]'
DRAFT_VERSION_BADGE = '[data-testid="draft-version-badge"]'
APPROVE_AND_SEND_BUTTON = '[data-testid="draft-approve-send-button"]'
SENDING_PROGRESS_SPINNER = '[data-testid="sending-progress-spinner"]'
TOAST_SUCCESS = '[data-testid="toast-success-notification"]'
TOAST_ERROR = '[data-testid="toast-error-notification"]'

# Phase 6: Two-Pane, Editor, Diff, Alerts, and Send Modal
TWO_PANE_CONTAINER = '[data-testid="two-pane-container"]'
LEFT_PANE_EVIDENCE = '[data-testid="left-pane-evidence"]'
RIGHT_PANE_EDITOR = '[data-testid="right-pane-editor"]'
ALERT_COMPLAINT_DETECTED = '[data-testid="alert-complaint-detected"]'
ALERT_RETURN_REFUND_REQUEST = '[data-testid="alert-return-refund-request"]'
DRAFT_VERSION_TIMELINE = '[data-testid="draft-version-timeline"]'
DRAFT_VERSION_ITEM = '[data-testid="draft-version-item"]'
DRAFT_VERSION_AI_TAG = '[data-testid="draft-version-ai-tag"]'
DRAFT_SUBJECT_INPUT = '[data-testid="draft-subject-input"]'
DRAFT_WORD_COUNT = '[data-testid="draft-word-count"]'
DRAFT_CHAR_COUNT = '[data-testid="draft-char-count"]'
DIFF_VIEWER_CONTAINER = '[data-testid="diff-viewer-container"]'
DIFF_TOGGLE_BUTTON = '[data-testid="diff-toggle-button"]'
DIFF_LINE_ADDED = '[data-testid="diff-line-added"]'
DIFF_LINE_REMOVED = '[data-testid="diff-line-removed"]'
DIFF_LINE_UNCHANGED = '[data-testid="diff-line-unchanged"]'
DRAFT_REGENERATE_LANG_SELECT = '[data-testid="draft-regenerate-language-select"]'
DRAFT_NO_REPLY_BUTTON = '[data-testid="draft-no-reply-button"]'
DRAFT_MOVE_MANUAL_REVIEW_BUTTON = '[data-testid="draft-move-manual-review-button"]'
SEND_CONFIRM_MODAL = '[data-testid="send-confirm-modal"]'
SEND_MODAL_CONFIRM_BTN = '[data-testid="send-modal-confirm-button"]'
SEND_MODAL_CANCEL_BTN = '[data-testid="send-modal-cancel-button"]'

# User Management
USER_MGMT_LIST = '[data-testid="user-management-table"]'
USER_CREATE_BUTTON = '[data-testid="create-user-button"]'
USER_DISABLE_BUTTON_TEMPLATE = '[data-testid="disable-user-button-{user_id}"]'
LOCKOUT_ERROR_BANNER = '[data-testid="lockout-error-banner"]'

# Phase 7: Operations Dashboard, System Health & Retention
NAV_DASHBOARD = '[data-testid="nav-dashboard"]'
DASHBOARD_CONTAINER = '[data-testid="dashboard-container"]'
DASHBOARD_REFRESH_BTN = '[data-testid="dashboard-refresh-btn"]'
DASHBOARD_RETENTION_MODAL_BTN = '[data-testid="retention-modal-btn"]'
DASHBOARD_STATUS_BANNER = '[data-testid="dashboard-status-banner"]'
DASHBOARD_STATUS_BADGE = '[data-testid="system-overall-badge"]'
DASHBOARD_DB_STATUS = '[data-testid="system-db-status"]'
DASHBOARD_WORKER_HEARTBEAT = '[data-testid="system-worker-heartbeat"]'
DASHBOARD_WORKER_JOBS = '[data-testid="system-worker-jobs"]'
DASHBOARD_UPTIME_TEXT = '[data-testid="system-uptime-text"]'
DASHBOARD_STORE_MATRIX = '[data-testid="store-matrix-card"]'
DASHBOARD_STORE_ROW_WRYDECO = '[data-testid="store-row-wrydeco"]'
DASHBOARD_STORE_ROW_CHILLGEN = '[data-testid="store-row-chillgen"]'
DASHBOARD_STORE_ROW_PREAUREUM = '[data-testid="store-row-preaureum"]'
DASHBOARD_STORE_ROW_JEMINISE = '[data-testid="store-row-jeminise"]'
DASHBOARD_QUEUE_DEPTH_CARD = '[data-testid="queue-depth-card"]'
DASHBOARD_SLA_WARNING = '[data-testid="sla-warning-banner"]'
DASHBOARD_QUEUE_READY = '[data-testid="queue-counter-ready_to_review"]'
DASHBOARD_QUEUE_MANUAL = '[data-testid="queue-counter-needs_manual_review"]'
DASHBOARD_QUEUE_PRODUCT = '[data-testid="queue-counter-product_inquiry"]'
DASHBOARD_QUEUE_RECENT_ORDER = '[data-testid="queue-counter-recent_order"]'
DASHBOARD_QUEUE_COMPLAINT = '[data-testid="queue-counter-complaint"]'
DASHBOARD_QUEUE_SPAM = '[data-testid="queue-counter-spam"]'
DASHBOARD_QUEUE_SENT = '[data-testid="queue-counter-sent"]'
DASHBOARD_PROXY_CARD = '[data-testid="proxy-health-card"]'
DASHBOARD_PROXY_EXIT_IP = '[data-testid="proxy-exit-ip"]'
DASHBOARD_PROXY_LATENCY = '[data-testid="proxy-latency"]'
DASHBOARD_AUDIT_CARD = '[data-testid="recent-audit-card"]'
DASHBOARD_AUDIT_TABLE = '[data-testid="audit-table"]'
DASHBOARD_AUDIT_ROW_FIRST = '[data-testid="audit-row-0"]'
RETENTION_MODAL_OVERLAY = '[data-testid="retention-modal-overlay"]'
RETENTION_DAYS_INPUT = '[data-testid="retention-days-input"]'
RETENTION_DRYRUN_CHECKBOX = '[data-testid="retention-dryrun-checkbox"]'
RETENTION_CONFIRM_CHECKBOX = '[data-testid="retention-confirm-checkbox"]'
RETENTION_EXECUTE_BTN = '[data-testid="retention-execute-btn"]'
RETENTION_CANCEL_BTN = '[data-testid="retention-cancel-btn"]'
RETENTION_RESULT_SUMMARY = '[data-testid="retention-result-summary"]'
